DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS userapp;

CREATE TABLE brand (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(1000),
                       image VARCHAR(255)
);

CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description VARCHAR(1000),
                          image VARCHAR(255)
);

CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         description TEXT,
                         brand_id BIGINT,
                         image VARCHAR(255),
                         ean VARCHAR(20),
                         price DOUBLE PRECISION,
                         discount INTEGER,
                         stock INTEGER,
                         CONSTRAINT fk_product_brand
                             FOREIGN KEY (brand_id)
                                 REFERENCES brand(id)
);

CREATE TABLE product_category (
                                  product_id BIGINT NOT NULL,
                                  category_id BIGINT NOT NULL,
                                  PRIMARY KEY (product_id, category_id),
                                  CONSTRAINT fk_product_category_product
                                      FOREIGN KEY (product_id)
                                          REFERENCES product(id),
                                  CONSTRAINT fk_product_category_category
                                      FOREIGN KEY (category_id)
                                          REFERENCES category(id)
);

CREATE TABLE event (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       description TEXT,
                       event_time TIMESTAMP,
                       event_type VARCHAR(255),
                       event_user_name VARCHAR(255),
                       message TEXT,
                       image VARCHAR(255)
);

CREATE TABLE userapp (
                         user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR(255) NOT NULL,
                         first_name VARCHAR(255),
                         last_name VARCHAR(255),
                         email VARCHAR(255) NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         birth_date DATE,
                         phone INTEGER,
                         registration_date TIMESTAMP
);

CREATE TABLE roles (
                       rol_id VARCHAR(50) PRIMARY KEY,
                       rol_description VARCHAR(255)
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            rol_id VARCHAR(50) NOT NULL,
                            PRIMARY KEY (user_id, rol_id),
                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES userapp(user_id),
                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (rol_id)
                                    REFERENCES roles(rol_id)
);

CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id BIGINT,
                           product_id BIGINT NOT NULL,
                           units INTEGER NOT NULL,
                           updated_at TIMESTAMP,
                           CONSTRAINT fk_cart_item_user
                               FOREIGN KEY (user_id)
                                   REFERENCES userapp(user_id),
                           CONSTRAINT fk_cart_item_product
                               FOREIGN KEY (product_id)
                                   REFERENCES product(id)
);